" General
set history=500                     " Set history in VIM to 500
set number                          " Show line numbers (shown on side)
syntax on                           " Syntax highlighting is fun and makes this usable as an editor
set linebreak                       " Set linebreak to prevent words from being split across lines
set showbreak=+++                   " Show line breaks with +++
set showmatch                       " Highlight matching brace
set ruler                           " Show row and column ruler info
set undolevels=1000                 " Number of undo levels
set backspace=indent,eol,start      " Backspace behavior
:set mouse=a

" Copy and paste behavior
set clipboard=unnamedplus           " Use system clipboard

" Searching
set hlsearch                        " Highlight all search results
set smartcase                       " Enable smart-case search
set ignorecase                      " Case insensitive searching
set incsearch                       " Searches for strings incrementally 

" Indenting 
set autoindent                      " Automatically indent new lines
filetype plugin indent on           " File type based indention
set smarttab
set noexpandtab			    
set indentexpr=
