### Setting Environment variables
LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 # Sets language variables
PATH=$PATH:$HOME/.local/bin:$HOME/.gem/ruby/2.7.0/bin # Sets path variable
EDITOR=vim # Default editor, mine is vim
