### Things that will be used by zsh 
source ~/.zsh/zshprompt
source ~/.zsh/aliases
source ~/.zsh/history

### Auto Completions
zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit
compinit

### Plugins go here
fpath=(~/.zsh/zsh-completions/src $fpath)
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
